version: "3.8"

services:
  frontend_web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend_web
    volumes:
      - .:/app
    ports:
      - "3000:80" # React 기본 포트 3000, Nginx에서 80으로 서빙
    depends_on:
      - backend_web # ✅ 백엔드 컨테이너가 실행된 후 실행
    networks:
      - shared_network # ✅ 백엔드와 같은 네트워크 사용

networks:
  shared_network:
    external: true # ✅ 이미 생성된 네트워크 사용
