version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - shared_network # ✅ 백엔드와 같은 네트워크 사용

networks:
  shared_network:
    external: true # ✅ 백엔드 네트워크와 연결
