name: Frontend Docker Image CI

on:
  push:
    branches:
      - ci-test 
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.14.0'  # Node.js 버전 확인 필요!

      - name: Install Dependencies
        run: |
          cd hanbangbo  
          npm install

      - name: Build React App
        run: |
          cd hanbangbo  
          npm run build

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/hanbangbo-front:latest

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/hanbangbo-front:latest

      - name: Trigger infra-deploy repository deployment
        run: |
          RESPONSE=$(curl -X POST -s -o /dev/null -w "%{http_code}" \
               -H "Authorization: token ${{ secrets.INFRA_DEPLOY_KEY }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/HanBangBo/infra-deploy/dispatches \
               -d '{"event_type":"front"}')

          if [ "$RESPONSE" -ne 204 ]; then
            echo "❌ GitHub API 요청 실패! 응답 코드: $RESPONSE"
            exit 1
          else
            echo "✅ GitHub API 요청 성공! 응답 코드: $RESPONSE"
          fi

